### ISSUE TITLE
Not able to load .Jpg image file..

### ISSUE THREAD

**Issue by ganeshoab** [HYPJUDY/A4-paper-sheet-detection-and-cropping#2]
I want to load .jpg format image.
Because I have .bmp image file larger than 1920*1080 resolution and size is greater than 5 mb.
So I need to load .jpg file.
Could you please advise me to how can I load .jpg image file?

Thanks,
Ganesh

**Comment by HYPJUDY** [comment]
Since this code only support bmp format input, can you try to convert your jpg format image into bmp format? (e.g. convert by [ImageMagick](https://www.imagemagick.org/script/index.php)) Considering your large resolution image, you can resize it firstly.

**Comment by ganeshoab** [comment]
Thank you.

________________________________
